### ISSUE TITLE
Separator should be configurable for `stringValue` properties and functions

### ISSUE THREAD

**Issue by pfei5** [orchetect/SwiftRadix#15]
The separator for the `stringValue` [property](https://github.com/orchetect/SwiftRadix/blob/1.2.0/Sources/SwiftRadix/Radix/Radix%20Collection%20Methods.swift#L14) and methods  is hard-coded to a space " ".
This increases the size of the resulting string unnecessarily by something like 30%. 
We have storage constraints on iOS and especially on watchOS.
IMHO the separator should be an empty string, but at the very least configurable.

Thank you for an otherwise amazingly convenient and tidy library.

**Comment by orchetect** [comment]
Yes there's a few missing customization points that would be worth adding added including these.

I can push a release fairly soon since they would mostly be defaulted parameters so it shouldn't be code-breaking.

**Comment by Proper-Job** [comment]
Wow, that's great, thank you so much!

**Comment by orchetect** [comment]
Release 1.3.0 includes the changes. Let me know if that works for you.
