### ISSUE TITLE
Add a Package.swift

### ISSUE THREAD

**Issue by xanderdunn** [orchetect/SwiftRadix#2]
Add a Package.swift so that this project can be installed via Swift's package manager.

**Comment by orchetect** [comment]
Sure, I can add that in the next update and also set it up as a proper cross-platform framework as well. Just been meaning to get around to it.

**Comment by orchetect** [comment]
FYI, I am currently working on a massive overhaul of the library as a multiplatform framework SPM package with fixes, tweaks, and also including support for binary and octal, not just hex. As well as adding full unit tests. Just be patient. Once it's done, the library will be renamed SwiftRadix.

**Comment by orchetect** [comment]
New 1.0.0 release is now pushed. Enjoy!

Library has been renamed SwiftRadix, bringing new features and tweaks.

Swift Package Manager support has been added.

https://github.com/orchetect/SwiftRadix/releases/tag/1.0.0
